### ISSUE TITLE
The new user registry implementation makes the server mildly extremely unstable

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/openliberty-domino#10]
For some reason, running in a NotesThread hits "UnsatisfiedLinkError" on lsxbe even when a manual System.load of the same works fine. It's possible that the cause is the duplication of the class from the core JVM into the plugin.

**Comment by DanieleVistalli** [comment]
This problem is the reason why in CrossWorlds the loading of notes libraries was done by a system extension. I loaded it globally and the CrossWorlds (+ notes.jar) code was available to all applications with a single copy in the classloader

**Comment by jesse-gallagher** [comment]
That makes sense. For now, I worked around it by making a janky little REST API, but I imagine I'll revisit it when it comes to baking CrossWorlds in.
