### ISSUE TITLE
Investigate dynamically-configured external proxy

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/openliberty-domino#30]
It could make sense to embrace the Liberty style of having one Liberty instance per application, and then put a proxy in front of all of the apps and Domino, dynamically configured based on names.nsf and the individual server.xml configurations.

The proxy servlet that I adapted in the repo already is _okay_, but I'm not terribly confident in it. It'd make more sense to find an existing standalone proxy server to use - I don't know if nginx would make sense here, but it'd certainly do the job.

Along with this, it would make sense to either always or optionally assign dynamic ports to the server.xml configs while writing them out to the filesystem.

**Comment by jesse-gallagher** [comment]
This is partially implemented by way of [Undertow](https://undertow.io) configured in the NSF and picking up on opted-in apps. Several important tasks remain:

- Add SSL support (attach keyrings in the NSF, or also possibly read from a kyr file)
- Dynamic refresh when the config changes
- Send $WS headers to Domino
- Send X-Forwarded-* for others
- Auto-apply proxy config in Liberty server.xml? This could be an "integration features" option
- Add to the RunJava build
- Switch to embedding the JAR inside the service bundle to avoid classpath contamination

**Comment by DanieleVistalli** [comment]
@jesse-gallagher would you consider: https://spring.io/projects/spring-cloud-gateway

We are working with it on another scenario where we have this kind of "api gateway / mesh" need and it's quite powerful.

What you described above can be implemented with a set of filters and all kind of transformations / federation can be done.

* Non blocking (based on spring reactor)
* Rich set of filters including rate limiting
* Fallback / circuit breaker behaviour
* Native extensibile management api (actuator)
* Packages as fat-jar

**Comment by jesse-gallagher** [comment]
That’s certainly worth considering, though I’ve had good luck with Undertow so far. Fortunately, the specific task is abstracted away mostly, so it wouldn’t be a big deal to swap implementations if I want to.
