### ISSUE TITLE
Consider downloading the runtime dynamically instead of bundling it in the plugin

### ISSUE THREAD

**Issue by jesse-gallagher** [OpenNTF/openliberty-domino#7]

**Comment by jesse-gallagher** [comment]
The Aether library should be able to fetch it from Maven Central without having to assume URLs: https://github.com/eclipse/aether-demo/blob/master/aether-demo-snippets/pom.xml

**Comment by DanieleVistalli** [comment]
This seems to be "good stuff". It of course increases the footprint of the solution.

It could work in 2 ways:

1. As part of the configuration database resolving artifacts at configuration (the httpservice then picks the url and acts as it does now)
1. Completely embedded in the service so in the configuration you only "pick" the version / artifact
